[background-image="images/pubquiz.webp",background-opacity="1.0"]
[%notitle]
== [white]*Quiz*




[.lightbg,background-image="images/pubquiz.webp",background-opacity="0.25"]
=== Immutable

* Why is immutable considered good? Name 3 reasons.


[.notes]
--
. No need to reason about possible states. There is only one, that after construction. +
  By the way a Java String is immutable, so a json document as String is too.
. Can be freely copied (think caches) without affecting or introducing caching problems. +
 (An immutable object is never written to, after instantiation) so no cache line invalidation.
. Speed.
. The first two make the functional/immutable style of functional languages so appealing.
. OO at the beginning was very state-full. Java think java beans. Now more and more functional style
  is promoted. With the combination of lambdas and streams this became even more popular.
--

[.lightbg,background-image="images/pubquiz.webp",background-opacity="0.25"]
=== What is more important

* Productivity in writing or ease of understanding/reading?

[.notes]
--
If you are payed by code-lines, then forget all of this.
--
